name: Promote to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image tag to deploy (e.g., dev-v1.2.3)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: fastapi-app


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Prod with Terraform
        run: |
          echo "Deploying image tag: ${{ github.event.inputs.version }}"
          cd terraform/prod
          terraform init
          terraform apply -auto-approve -var="image_tag=${{ github.event.inputs.version }}"
