name: Promote to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image tag to deploy (e.g., dev-v1.2.3)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: fastapi-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Deploy to Prod with Terraform
        run: |
          IMAGE_TAG=${{ github.event.inputs.version }}
          echo "Deploying image tag: $IMAGE_TAG"
          cd terraform/prod
          terraform init
          terraform apply -auto-approve \
            -var="image_tag=$IMAGE_TAG" \
            -var="execution_role_arn=${{ secrets.ECS_EXECUTION_ROLE }}" \
            -var="task_role_arn=${{ secrets.ECS_TASK_ROLE }}" \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Deploy frontend to S3
        run: |
          aws s3 cp frontend/index.html s3://commversemyapp-prod








